import type { Metadata } from "next";
import { Inter } from "next/font/google";

import MaterialUiProvider from "@/providers/material-ui-provider";
import ReactQueryProvider from "@/providers/react-query-provider";
import { SessionProvider } from "@/providers/session-provider";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <ReactQueryProvider>
            <MaterialUiProvider>{children}</MaterialUiProvider>
          </ReactQueryProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
